Add Google sheet capability
thealphadollar/vanilla-i18n pull request #10
Opened 2021-06-08 17:22 UTC by RandallWert

# Pull Request

## I created a new Python program "csv_or_sheet_to_vanilla_i18.py" to add the capability of getting the csv data from a Google sheet.

## I detect how many parameters were entered by the user. If three, then the second and third parameters are considered to be the SheetID and worksheet name, and the URL is built from them. In the main function, I look for the presence of "google.com" in the path; if it is found, this indicates that a sheet should be read via the URL. Otherwise, it is assumed that a local csv file should be read.

## I tested again the csv and sheet that you provided, so running it against those should verify that it works.

## This change creates the capability of reading a Google sheet, not just a local csv file.

- [√] Major (I think?)
- [ ] Minor
- [ ] Patch

## Description for the changelog

2021-06-09 15:32 UTC, thealphadollar requested changes
I tested and it works perfectly. Thanks @RandallWert . I would suggest some sanitation changes.

- Please update the code in the existing python script instead of adding a new one.
- Have default option for worksheet set as "Sheet1". When the user passes only a single param, check if it's a file path. Otherwise assume it to be sheet ID.
- I don't think we should allow entry of URL since it may not be consistent. For instance, I believed a direct sheet link from the browser had to be put. I was wrong.
- Update the readme with details on how the script works. The existing README.md inside `csv_to_vanilla-i18n` already contains some instructions.

2021-06-09 18:14 UTC, RandallWert commented
Hi, thanks for your feedback! I understand all of your points except the third one. I'm not sure exactly what I should change for that one. Should I just make a note in the readme, instructing the user not to enter an entire URL, but only the sheet ID (and possibly the worksheet name, if different from the default)?

2021-06-09 19:01 UTC, thealphadollar commented
On the third point, I meant to remove the feature to add the URL as a specific URL pattern is required. Users may be more confused with that.

2021-06-09 19:21 UTC, RandallWert commented
OK, I'm trying to prevent that confusion by putting the URL pattern in the code, rather than asking the user to enter it. The user only has to be concerned with the sheet ID (and possibly the worksheet name, if different than the default).

I did my best to make the changes you requested to the Python script and the readme. I just pushed another commit with those changes.

Thank you again for the opportunity to work on this, and please let me know if I should refine the code any further.

2021-06-09 20:15 UTC, thealphadollar requested changes
LGTM. Thanks for adding exhaustive details to the README.

I've requested some more minor changes. Please push them and we can merge the changes.

2021-06-09 20:15 UTC, thealphadollar commented on csv_to_vanilla-i18n/README.md
> +* You can specify the sheet ID and worksheet name of a Google Sheets worksheet, in that order, separated by a space. (Do NOT enter the entire URL to the Google Sheet.)
```suggestion
* You can specify the sheet ID and worksheet name of a Google Sheets worksheet, in that order, separated by a space. Eg. `python3 csv_to_vanilla_i18n.py 1KfPLetq4VUvEApiGtWEUuQUhAYCrocyLmyiHV2cl_ks Sheet1`
```

2021-06-09 20:15 UTC, thealphadollar commented on csv_to_vanilla-i18n/README.md
> +* You can specify only the sheet ID and let the worksheet name default to ‘Sheet1’.
```suggestion
* You can specify only the sheet ID and let the worksheet name default to ‘Sheet1’. Eg. `python3 csv_to_vanilla_i18n.py 1KfPLetq4VUvEApiGtWEUuQUhAYCrocyLmyiHV2cl_ks`
```

2021-06-09 20:15 UTC, thealphadollar commented on csv_to_vanilla-i18n/README.md
> +* You can specify only the path to a local language CSV file. Be sure to include the .csv extension.
```suggestion
* You can specify only the path to a local language CSV file. Be sure to include the .csv extension. Eg. `python3 csv_to_vanilla_i18n.py /path/to/csv`
```

2021-06-09 20:15 UTC, thealphadollar commented on csv_to_vanilla-i18n/README.md
> +* You can omit the parameters completely. Then you will be prompted for the name of a local language CSV file. Be sure to include the .csv extension.
```suggestion
* You can omit the parameters completely. Then you will be prompted for the name of a local language CSV file. Be sure to include the .csv extension. Eg. `python3 csv_to_vanilla_i18n.py`
```

2021-06-09 20:15 UTC, thealphadollar commented on csv_to_vanilla-i18n/csv_or_sheet_to_vanilla_i18.py
> +#!/usr/bin/env python3
Please remove this file as the changes have been made in the original py script.

2021-06-09 20:45 UTC, RandallWert commented
OK, made those changes to the readme, and hopefully removed that unnecessary .py script successfully. (That's my first experience with that -- I'm still pretty new to making open source contributions.)

2021-06-10 04:59 UTC, thealphadollar approved these changes
LGTM. Your contribution is amazing considering it's your first time to open source. Looking forward to interacting more with you Randall.

2021-06-10 04:59 UTC, merged

2021-06-10 06:14 UTC, RandallWert commented
Thank you so much! It was a pleasure and helped me learn a lot! I appreciate the opportunity to contribute, and I look forward to more collaboration with you.